apiVersion: v1
kind: Namespace
metadata:
  name: hd-namespace
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: hd-tcp-service
  namespace: hd-namespace
  labels:
    app: hd-tcp-app
spec:
  ports:
  - port: 9000
    name: tcp
  selector:
    app: hd-tcp-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hd-tcp-app
  namespace: hd-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hd-tcp-app
  template:
    metadata:
      labels:
        app: hd-tcp-app
    spec:
      containers:
      - name: hd-tcp-app
        image: hd-tcp-app-image
        ports:
        - containerPort: 9000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hd-tcp-destination-rule
  namespace: hd-namespace
spec:
  host: hd-tcp-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: hd-namespace
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hd-tcp-virtual-service
  namespace: hd-namespace
spec:
  hosts:
  - hd-tcp-service
  tcp:
  - match:
    - port: 9000
    route:
    - destination:
        host: hd-tcp-service
        port:
          number: 9000
