apiVersion: v1
kind: Namespace
metadata:
  name: your-namespace
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: my-http-service
  namespace: your-namespace
  labels:
    app: my-http-app
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: my-http-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-http-app
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-http-app
  template:
    metadata:
      labels:
        app: my-http-app
    spec:
      containers:
      - name: my-http-app
        image: my-http-app-image
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-http-destination-rule
  namespace: your-namespace
spec:
  host: my-http-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-http-virtual-service
  namespace: your-namespace
spec:
  hosts:
  - my-http-service
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        prefix: "/v1"
    route:
    - destination:
        host: my-http-service
        subset: v1
  - match:
    - uri:
        prefix: "/v2"
    route:
    - destination:
        host: my-http-service
        subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: your-namespace
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: your-namespace
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: my-authorization-policy
  namespace: your-namespace
spec:
  selector:
    matchLabels:
      app: my-http-app
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/your-namespace/sa/my-service-account"]
  - to:
    - operation:
        methods: ["GET", "POST"]
