apiVersion: v1
kind: Namespace
metadata:
  name: hd-namespace
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: hd-http-service
  namespace: hd-namespace
  labels:
    app: hd-http-app
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: hd-http-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hd-http-app
  namespace: hd-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hd-http-app
  template:
    metadata:
      labels:
        app: hd-http-app
    spec:
      containers:
      - name: hd-http-app
        image: hd-http-app-image
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hd-http-destination-rule
  namespace: hd-namespace
spec:
  host: hd-http-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hd-http-virtual-service
  namespace: hd-namespace
spec:
  hosts:
  - hd-http-service
  gateways:
  - hd-gateway
  http:
  - match:
    - uri:
        prefix: "/v1"
    route:
    - destination:
        host: hd-http-service
        subset: v1
  - match:
    - uri:
        prefix: "/v2"
    route:
    - destination:
        host: hd-http-service
        subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hd-gateway
  namespace: hd-namespace
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
